# Waybar privacy status bindings

# Mic mute toggle
bind = , XF86AudioMicMute, exec, ~/.config/waybar/scripts/toggle-mic.sh

# Camera status toggle
# My ASUS ProArt F10 is unreliable, so use SUPER+C in my case
bind = SUPER, C, exec, ~/.config/waybar/scripts/toggle-camera-state.sh
